name: CI/CD Pipeline with DockerHub & EC2

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    name: Build & Push to DockerHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nodeapp:latest .

      - name: Push Docker image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/nodeapp:latest

  deploy:
    name: Deploy to EC2 Server
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: SSH and Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/nodeapp:latest
            docker stop nodeapp || true
            docker rm nodeapp || true
            docker run -d -p 5050:5050 --name nodeapp ${{ secrets.DOCKERHUB_USERNAME }}/nodeapp:latest
